workflows:
  android-build:
    name: Android Build
    instance_type: mac_mini_m2
    scripts:
      - name: Grant Gradle permissions
        script: chmod +x ./gradlew
      
      - name: Build Debug APK
        script: ./gradlew assembleDebug
    
    artifacts:
      - app/build/outputs/**/*.apk
