format_version: "11"
default_step_lib_source: https://github.com/bitrise-steplib/bitrise-steplib.git

project_type: android

workflows:
  primary:
    steps:
    - activate-ssh-key@4:
        run_if: '{{setup_ssh_key | regexMatch ".*"}}'
    - git-clone@6: {}
    - cache-pull@2: {}
    - script@1:
        title: Accept Android Licenses
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -ex
            yes | sdkmanager --licenses || true
    - install-missing-android-sdk-components@3:
        inputs:
        - gradlew_path: ./gradlew
    - android-build@1:
        inputs:
        - project_location: $BITRISE_SOURCE_DIR
        - module: app
        - variant: debug
    - cache-push@2: {}
    - deploy-to-bitrise-io@2: {}

meta:
  bitrise.io:
    stack: linux-docker-android-22.04
    machine_type_id: standard
